#pragma once

#define CMD_POINT_ADD 0x30
#define CMD_POINT_MODIFY 0x31
#define CMD_POINT_DELETE 0x32

#define CMD_LINE_ADD 0x33
#define CMD_LINE_MODIFY 0x34
#define CMD_LINE_DELETE 0x35

#define CMD_STAFF_ADD 0x36
#define CMD_STAFF_MODIFY 0x37
#define CMD_STAFF_DELETE 0x38

#define CMD_EMERGENCY_ADD 0x39
#define CMD_EMERGENCY_MODIFY 0x3A
#define CMD_EMERGENCY_DELETE 0x3B

#define CMD_ORG_ADD 0x3C
#define CMD_ORG_MODIFY 0x3D
#define CMD_ORG_DELETE 0x3E

#define CMD_DEVICE_ADD 0x40
#define CMD_DEVICE_MODIFY 0x41
#define CMD_DEVICE_DELETE 0x42